apiVersion: v1
kind: Service
metadata:
  name: flux-web
  namespace: flux-system
  labels:
    app.kubernetes.io/name: flux-operator
    app.kubernetes.io/component: web-ui
spec:
  type: NodePort
  ports:
    - name: http-web
      port: 9080
      targetPort: http-web
      nodePort: 30080
      protocol: TCP
  selector:
    app.kubernetes.io/name: flux-operator
