apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capi-child-1
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: super-cluster
  source:
    repoURL: https://github.com/EzzOps/Super-Cluster.git
    targetRevision: HEAD
    path: clusters/child/child-1
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
