apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: child-1-apps
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/child/child-1
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  kubeConfig:
    secretRef:
      name: kubeconfig-child-1
