apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - child-1-apps.yaml
  - remote-child-kustomization.yaml
  - sveltos/
  - flux-operator/flux-instance.yaml
  - flux-operator/flux-web-nodeport.yaml
  - flux-operator/git-secret.yaml
