apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-resources
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/child
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
