apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: baseline-addons
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: "*"
  syncMode: ContinuousWithDriftDetection
  helmCharts:
  - repositoryURL: https://kubernetes-sigs.github.io/metrics-server/
    repositoryName: metrics-server
    chartName: metrics-server/metrics-server
    chartVersion: v0.7.1
    releaseName: metrics-server
    releaseNamespace: kube-system
    helmChartAction: Install
  - repositoryURL: https://charts.cert-manager.io
    repositoryName: cert-manager
    chartName: cert-manager/cert-manager
    chartVersion: v1.15.0
    releaseName: cert-manager
    releaseNamespace: cert-manager
    helmChartAction: Install
