apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: baseline-addons
spec:
  clusterSelector:
    matchLabels:
      env: prod
  helmCharts:
  - chartName: metrics-server/metrics-server
    chartVersion: v0.7.1
    helmChartAction: Install
    releaseName: metrics-server
    releaseNamespace: kube-system
    repositoryName: metrics-server
    repositoryURL: https://kubernetes-sigs.github.io/metrics-server/
  - chartName: cert-manager/cert-manager
    chartVersion: v1.15.0
    helmChartAction: Install
    releaseName: cert-manager
    releaseNamespace: cert-manager
    repositoryName: cert-manager
    repositoryURL: https://charts.cert-manager.io
  syncMode: ContinuousWithDriftDetection
