apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: child-2
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.0.0/16
    services:
      cidrBlocks:
        - 10.96.0.0/12
  topology:
    class: quick-start
    version: v1.36.2
    controlPlane:
      replicas: 1
    workers:
      machineDeployments:
        - class: default-worker
          name: md-0
          replicas: 1
